# Generated by Django 6.0.2 on 2026-02-17 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Количество товара на складе')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='Артикул товара')),
                ('attributes', models.ManyToManyField(to='product.attributevalue', verbose_name='Атрибуты товара')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='product.product', verbose_name='Товар')),
            ],
        ),
    ]
