# Generated by Django 6.0.2 on 2026-02-25 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productvariant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('big_title', models.CharField(max_length=100, verbose_name='Большое название')),
                ('little_title', models.CharField(max_length=100, verbose_name='Мелкие текста')),
                ('img', models.ImageField(upload_to='slider/')),
                ('link', models.CharField(max_length=255, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'слайдер',
                'verbose_name_plural': 'Слайдер',
            },
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'verbose_name': 'Варианты товаров', 'verbose_name_plural': 'вариант товара'},
        ),
    ]
